# Generated by Django 3.0.1 on 2019-12-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture_pic',
            new_name='profile_pic',
        ),
    ]
